apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    app.kubernetes.io/name: alertmanager
  namespace: monitoring
data: 
  config.yaml: |
    global:
      smtp_from: 'alertmanager@gmail.com'
      smtp_smarthost: smtp.gmail.com:465
      smtp_auth_username: vladozz23@gmail.com
      smtp_auth_identity: vladozz23@gmail.com
      smtp_auth_password: pisxijhlxexflfhu
      smtp_require_tls: false
    templates:
    - '/etc/alertmanager-template/*.tmpl'
    route:
      receiver: email
      group_wait: 10s
      repeat_interval: 30m
      group_by: 
      - alertname
      - priority
    receivers:
    - name: email
      email_configs:
      - to: 'vladoz77@yandex.ru'
        send_resolved: true

