apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  labels:
    app: grafana
spec:
  project: monitoring
  sources:
  - repoURL: https://github.com/vladoz77/victoria-metrics-monitoring.git
    targetRevision: HEAD 
    ref: myRepo
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.14.2
    helm:
      valueFiles:
        - $myRepo/grafana/grafana.yaml
  # - repoURL: https://github.com/vladoz77/argocd.git
  #   targetRevision: HEAD 
  #   path: monitoring-single/grafana/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true