apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: kube-state-metrics
spec:
  project: monitoring
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts 
    chart: kube-state-metrics
    targetRevision: 5.19.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true