apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 35Mi
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: status-config-vol
          mountPath: /etc/nginx/conf.d/status.conf
          subPath: status.conf
      - image: nginx/nginx-prometheus-exporter:latest
        name: nginx-prometheus-exporter
        args:
            - "--nginx.scrape-uri=http://localhost:8080/stub_status"
        ports:
        - name: metrics
          containerPort: 9113 
        resources:
          requests:
            cpu: 10m
            memory: 35M
          limits:
            cpu: 300m
            memory: 600M
      volumes:
      - name: status-config-vol
        configMap:
          name: status-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: status-config
  namespace: nginx
data:
  status.conf: |-
    server {
      listen 8080;

      location /stub_status {
        stub_status;
      }

    }
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: nginx-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 9113
    targetPort: 9113
    name: metrics
  selector:
    app: nginx-server
