namespaceOverride: monitoring

prometheus:
  url: http://vmsingle.monitoring.svc
  port: 8428

replicas: 1

rules:
  default: false
  custom:
    - seriesQuery: 'nginx_http_requests_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'

    - seriesQuery: 'http_requests_total'
      resources:
         template: <<.Resource>>
      name:
        matches: "^(.*)_total"
        as: ""
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'

    